# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
command:
  print_pipeline_id:
    description: Command to print pipeline id
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  pipleline_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - print_pipeline_id
workflows:
  say-hello-workflow:
    jobs:
